### ISSUE TITLE
Mithril Platebody will not open correctly.

### ISSUE THREAD

**Issue by STNwin** [Hannah-GBS/notenoughrunes#5] opened 2023-09-10 20:45 UTC
The gold and trimmed variants open correctly however the regular mithril platebody does nothing when clicked on in the menu.
Item menu should open regardless of sources/uses.

**Comment by Hannah-GBS** [comment] 2023-09-10 21:07
Looks like this is caused by the Drops section for mithril platebody (and several other items) having a "smithing" source, for when repairing a [Damaged armour](https://oldschool.runescape.wiki/w/Damaged_armour) at an Armour Stand.

Shouldn't be hard to fix. I'll take a look at it now.

**Comment by Hannah-GBS** [comment] 2023-09-17 15:11
Fixed in cabbf15

**Closed as completed by Hannah-GBS** 2023-09-17 15:11 UTC
